default: &default
  adapter: postgresql
  encoding: unicode
  host: monorail.proxy.rlwy.net
  port: 42240
  database: railway
  username: postgres
  password: 46-fcBbcaA2F*ebBbGBg21-FDCCb2cEA


development:
  <<: *default
#  database: myapp_development
#  username: postgres
#  password: 
#  host: db

test:
  <<: *default
#  database: myapp_test
# username: postgres
#  password: 

production:
  <<: *default